//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaintStoragev2MVC.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;

    
    public partial class Paint
    {
        
        public Nullable<int> RAL { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public Nullable<int> Storage { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public int PaintID { get; set; }
    }
    

    
}


